/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cbear' at '12/1/16 12:07 PM' with Gradle 3.0
 *
 * @author cbear, @date 12/1/16 12:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
